---
name: Semgrep

on:
  pull_request:
    branches:
      - "master"
      - "release-**"

jobs:
  semgrep-lsc-log:
    uses: TykTechnologies/github-actions/.github/workflows/semgrep.yaml@7ae95a15737fa09302630cf18b6e6c11078ef3de
    with:
      config: "./lsc/log/rules/log.yml"
